### ISSUE TITLE
Add AWS::Serverless::Function Support

### ISSUE THREAD

**Issue by jkassel** [shalupov/idea-cloudformation#103]
Currently not a supported resource type.  Should work with proper transform version.

**Comment by ShaunEgan** [comment]
I would like this too.

**Comment by keyboard-jockey** [comment]
Yes, please!  My cf templates are already using this, and I have to ignore the syntax errors on every commit or code analysis.

**Comment by shalupov** [comment]
fixed in 0.5.39
