### ISSUE TITLE
EventSelectors property in the AWS::CloudTrail::Trail resource

### ISSUE THREAD

**Issue by gchiesa** [shalupov/idea-cloudformation#106]
Hi,

I'm using the AWS::CloudTrail::Trail resource and the property EventSelectors is not recognised as valid property, but it's an actual property available for the resource. 

Here the snippet:
![screen shot 2017-09-08 at 10 45 31](https://user-images.githubusercontent.com/4255029/30203624-e76dae10-9482-11e7-8d67-81c5263ced68.png)

**Comment by shalupov** [comment]
fixed in 0.5.39
