### ISSUE TITLE
Allow other kind for file extension

### ISSUE THREAD

**Issue by alvinlin123** [shalupov/idea-cloudformation#108]
Currently it looks like the plugin only support `*.json`, `*.yaml` and `*.template`. Would it be possible to support custom file extension? For example, I have a cloudformation template that ends with `*.yml.mustache`; it would be nice if I have configure the plugin to be effective for that file extension too.

**Comment by shalupov** [comment]
It's possible to assign additional extensions in File -> Settings -> Editor -> File Types
