### ISSUE TITLE
Resolve resource properties for Fn::GetAtt

### ISSUE THREAD

**Issue by TarasTielkes** [shalupov/idea-cloudformation#11]
Most resource types have readable properties in addition to settable/writable ones.
They can be referenced from other resource declarations by using _Fn::GetAtt_
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html

Just as for regular attributes, code completion and validation in _Fn:GetAtt_ expressions would be very useful.

**Comment by shalupov** [comment]
Long time here
