### ISSUE TITLE
Description is not recognised in intellij

### ISSUE THREAD

**Issue by FlemmingBehrend** [shalupov/idea-cloudformation#110]
Creating a yaml template using the plugin in IntelliJ gives the following error in descriptions in resources:

![image](https://user-images.githubusercontent.com/1967934/31338000-f63b6548-acfd-11e7-83d7-8d275bbadd85.png)

I think the problem is in the `src/main/kotlin/com/intellij/aws/cloudformation/model/CfnResourceNode.kt`, it seams `Description` is missing.

https://github.com/shalupov/idea-cloudformation/blob/b0ff8e677b322f2ce11a6f496932dc1f53d2bddb/src/main/kotlin/com/intellij/aws/cloudformation/model/CfnResourceNode.kt#L3-L8

**Comment by shalupov** [comment]
Could you point me to Cloud Formation documentation?
For description I only see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-description-structure.html and it's not under resource

**Comment by FlemmingBehrend** [comment]
You are right it is only for template, don't know how I can miss that, but thanks for pointing it out 👍 

I will clone this issue and delete my `Description` field 😺
