### ISSUE TITLE
File type detection is too slow

### ISSUE THREAD

**Issue by ignatov** [shalupov/idea-cloudformation#111]
Please see `com.intellij.aws.cloudformation.JsonCloudFormationFileType.isMyFileType` and `com.intellij.aws.cloudformation.YamlCloudFormationFileType.isMyFileType`

![image](https://user-images.githubusercontent.com/426890/31485143-76be8fc6-af3b-11e7-9630-095cf84328c9.png)

Original issues – https://youtrack.jetbrains.com/issue/GO-3648 and https://youtrack.jetbrains.com/issue/GO-4633

**Comment by shalupov** [comment]
fixed in 0.5.41, released to plugin repository
