### ISSUE TITLE
Multiple transforms in cloudformation template

### ISSUE THREAD

**Issue by JonasJurczok** [shalupov/idea-cloudformation#115]
Hi,

I'm using AWS SAM to deploy Lambda Functions in a CodeStar context.
The cloudformation template that CodeStar generates starts with
```
AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::CodeStar
```

This gets marked as an Error ("String literal expected").
Is this an existing issue or am I making a mistake?

Thanks for the plugin :D

**Comment by shalupov** [comment]
It's bug, documentation states that it may be multiple transformations.
see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
