### ISSUE TITLE
Cognito UserPool Attributes show error

### ISSUE THREAD

**Issue by bamapookie** [shalupov/idea-cloudformation#116]
!GetAtt UserPool.Arn
!GetAtt UserPool.ProviderName
!GetAtt UserPool.ProviderUrl
all show as errors for UserPool Type AWS::Cognito::UserPool.  More information on the valid return types are listed here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#w2ab2c21c10d250c11

**Comment by shalupov** [comment]
fixed in 0.5.42

**Comment by bamapookie** [comment]
I am still seeing these errors in 0.5.42.
