### ISSUE TITLE
AWS::Cognito::UserPool Arn return attribute not mapped

### ISSUE THREAD

**Issue by xintellion** [shalupov/idea-cloudformation#119]
The Cloudformation UserPoolType  [return](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#w2ab2c21c10d250c11)  attribute doesnt seem to be mapped. 

When I try to reference the Arn attribute from a user pool resource with "Fn::GetAtt" intellij complains:
`Unknown attribute in resource type 'AWS::Cognito::UserPool': Arn`

Besides that, Thanks for the great tool!

**Comment by shalupov** [comment]
duplicates #121
