### ISSUE TITLE
Quick documentation popup support for resources and attributes

### ISSUE THREAD

**Issue by TarasTielkes** [shalupov/idea-cloudformation#12]
Ctrl-Q ("Quick JavaDoc Popup") support would be very useful when reading and authoring AWS CloudFormation templates.

Since the crawler is collecting resource and attribute names already, it would make sense to collect and provide the documentation text for them as well.

**Comment by shalupov** [comment]
fixed by c36861fd670af1d7febd40815c3c0d6173c589c9
