### ISSUE TITLE
HealthCheckGracePeriodSeconds not recognized

### ISSUE THREAD

**Issue by carterlexy** [shalupov/idea-cloudformation#124]
HealthCheckGracePeriodSeconds is not recognized as valid for type AWS::ECS::Service

Documented here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-healthcheckgraceperiodseconds

**Comment by carterlexy** [comment]
IntelliJ IDEA 2018.1.1 (Ultimate Edition)
Build #IU-181.4445.78, built on April 9, 2018
JRE: 1.8.0_152-release-1136-b27 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3

AWS CloudFormation Plugin
Version: 0.5.42

Error is reported when using property "HealthCheckGracePeriodSeconds" on type "AWS::ECS::Service" as:

> Unknown resource type property: HealthCheckGracePeriodSeconds

**Comment by shalupov** [comment]
please try new plugin version 0.5.53
