### ISSUE TITLE
"Unknown resource type property: SSESpecification"

### ISSUE THREAD

**Issue by PatMyron** [shalupov/idea-cloudformation#125]
AWS CloudFormation added support for a new property of AWS::DynamoDB::Table 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-table-ssespecification.html

**Comment by shalupov** [comment]
Which IDE and which plugin version do you use? ssespecification is supported in the last version 0.5.42

**Comment by PatMyron** [comment]
IntelliJ IDEA 2018.1.1 (Community Edition)
Build #IC-181.4445.78, built on April 9, 2018
JRE: 1.8.0_152-release-1136-b27 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6

and plugin version 0.5.42

Just tried invalidating the caches and restarting and still seeing it

**Comment by akuma12** [comment]
I get the same thing, also using 0.5.42 with:
PyCharm 2018.1 (Community Edition)
Build #PC-181.4203.547, built on March 26, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 3.10.0-693.21.1.el7.x86_64

**Comment by shalupov** [comment]
fixed in 0.5.53
