### ISSUE TITLE
Unknown resource type property: BucketEncryption

### ISSUE THREAD

**Issue by jpfile** [shalupov/idea-cloudformation#126]
I'm getting an unknown resource type for the BucketEncryption property.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#cfn-s3-bucket-bucketencryption

IntelliJ IDEA 2018.1.1 (Community Edition)
Build #IC-181.4445.78, built on April 9, 2018
JRE: 1.8.0_152-release-1136-b27 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 8.1 6.3

**Comment by shalupov** [comment]
fixed in 0.5.53
