### ISSUE TITLE
Add support for AppSync resource attributes

### ISSUE THREAD

**Issue by elecnix** [shalupov/idea-cloudformation#130]
I can define an `AWS::AppSync::GraphQLApi`, but any references to its `ApiId` attribute gives a warning:

    Unknown attribute in resource type 'AWS::AppSync::GraphQLApi': ApiId less... (Ctrl+F1) 
    Under construction

Same for the `Name` of `AWS::AppSync::DataSource`.

**Comment by shalupov** [comment]
fixed in 0.5.68
