### ISSUE TITLE
*.template

### ISSUE THREAD

**Issue by persononomo** [shalupov/idea-cloudformation#134]
When I found this bug I researched and then I found this comment. This happened to me too. But I renamed all my files from *.template to *.json and everything works well.

----------------------------------------------------
https://plugins.jetbrains.com/plugin/7371-aws-cloudformation#comment=27851
Jaron Foster
Jul 03, 2018 01:19:16

I've actually experienced cpu spikes while using this plugin. While active the plugin would cause Intellij to spike up to 300% CPU usage. In addition, the project viewer window would constantly flicker between white/blue, which indicicates that this plugin doesn't play nicely with the "file highlight status" capabilities within Intellij. I'm not sure why this is happening and I am more than happy to provide more info if someone else has experienced this as well.

**Comment by mliner** [comment]
With few colleagues we have the same flickering problem for last few versions of this plugin. Also when I select *.template file in the project tree it automatically moves focus to the directory where the file resides.
Is it possible to put some priority for this as this plugin is very userfull for many people.

Version used: 0.5.69
Used within RubyMine and PyCharm

**Comment by shalupov** [comment]
I can't reproduce this issue locally.
Probably a screencast would help along with some notes ho to reproduce it

**Comment by shalupov** [comment]
Also please try IDEA 2018.3 EAP with plugin 0.6.5
