### ISSUE TITLE
Cannot format file

### ISSUE THREAD

**Issue by montao** [shalupov/idea-cloudformation#135]
If I want to "reformat code" using CF syntax, is that possible? If yes, how? I tried installing the plugin in IDEA 2018 community edition and it could analyze the file for errors but I could not "reformat code" after making some change. If the feature is available, where can I find it?

**Comment by shalupov** [comment]
There is build-in formatter for JSON and YAML files. It should be available for CF files.
I've tested it and `Code` -> `Reformat Code` works for me
