### ISSUE TITLE
Fix Support for Globals

### ISSUE THREAD

**Issue by asyba** [shalupov/idea-cloudformation#140]
Some tags are not supported like Runtime, CodeUri.
I add them in Globals, but then in the FunctionsLambda is marked red like is missing the CodeUri, Runtime properties.

Documentation from SAM:
https://github.com/awslabs/serverless-application-model/blob/a315215ac1d6275da962643572b821884e9c3b56/docs/globals.rst#lists-are-replaced

**Comment by orende** [comment]
Would be really nice to have this! Globals are an excellent way to reduce duplication in the CF files.

**Comment by bikerp** [comment]
I experience the same issue as @asyba.
I would really appreciate to have it fixed. Thanks in advance

**Comment by shalupov** [comment]
@bikerp @asyba Please try version 0.6.9. If it still does not work, please attach a code snippet here

**Comment by bikerp** [comment]
@shalupov I have the latest version installed and the error still persist. Here is the template snippet:

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Hello World

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs8.10

Resources:

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/hello/
      Handler: app.handler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: post

**Comment by asyba** [comment]
same as @bikerp

**Comment by shalupov** [comment]
Fixed in 0.6.11
