### ISSUE TITLE
Bucket Creating Issue with PublicAccessBlockConfiguration Nesting

### ISSUE THREAD

**Issue by clintonmagro** [shalupov/idea-cloudformation#141]
There is a problem with Type `AWS::S3::Bucket`
When setting up PublicAccessBlockConfiguration the plugin expects it to be nested under `AccessControl` but should actually be under `Properties`

Expected by plugin (this is wrong):
Properties > AccessControl > PublicAccessBlockConfiguration

How it should be:
Properties > PublicAccessBlockConfiguration

Documented here too: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html

**Comment by shalupov** [comment]
Please check - 0.6.9 is released
