### ISSUE TITLE
Please add BillingMode to AWS::DynamoDB::Table

### ISSUE THREAD

**Issue by eranation** [shalupov/idea-cloudformation#142]
More details on the new property: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-billingmode

(if you have a quick guide / docs on how to edit this, I'll be happy to send a pull request... will save me some time digging in the code)

**Comment by shalupov** [comment]
Please check - 0.6.9 is released
