### ISSUE TITLE
Add Support for AWS::Lambda::LayerVersion

### ISSUE THREAD

**Issue by mtrubs** [shalupov/idea-cloudformation#143]
I am using this plugin (v0.6.5) in GoLand.

It is possible to define Layers for lambdas in CF templates now. However I get an error `Unknown CloudFormation resource type: AWS::Lambda::LayerVersion`. Similarly when I link the layer into a lambda function I get `Unknown resource type property: Layers`.

The documentation can be found here:
* [Lambda::LayerVersion](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-layerversion.html)
* [Lambda::Function.Layers](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-layers)

**Comment by shalupov** [comment]
Please check - 0.6.9 is released

**Comment by mtrubs** [comment]
looks great. thank you!
