### ISSUE TITLE
Compatible with IntelliJ 2018.3.4?

### ISSUE THREAD

**Issue by mcanlas** [shalupov/idea-cloudformation#144]
I installed your plug-in and I'm looking at my CF files but for some reason I'm not seeing any different behavior. There's no output or new UI.

Is this plug-in compatible with the latest IntelliJ 2018.3.4? Is there a way to debug why nothing is happening?

```
IntelliJ IDEA 2018.3.4 (Community Edition)
Build #IC-183.5429.30, built on January 29, 2019
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3
```

**Comment by rcollette** [comment]
Make sure your file has a template version in it.   I was not seeing any behavior without this.

```
AWSTemplateFormatVersion: "2010-09-09"
```

**Comment by mcanlas** [comment]
Hmm, I can't seem to reproduce. And there have been IntelliJ upgrades since.
