### ISSUE TITLE
Add support for AWS::SecretsManager::Secret

### ISSUE THREAD

**Issue by froehr** [shalupov/idea-cloudformation#145]
Hello,

can you please add support for the cloudformation ressource type AWS::SecretsManager::Secret?
The documentation can be found here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secret.html

Tanks in advance.

**Comment by shalupov** [comment]
Please check - 0.6.9 is released
