### ISSUE TITLE
Is validation scriptable?

### ISSUE THREAD

**Issue by iainelder** [shalupov/idea-cloudformation#153]
I have a deployment script that calls `validate-template` on all the template files before attempting to deploy them to AWS.

The `validate-template` API call, as I'm sure you know, misses a lot of errors that this plugin can reliably detect before deployment.

Would it be possible to script this plugin to validate my templates in a script instead of calling `validate-template`?

Thanks!

**Comment by shalupov** [comment]
Have you checked out https://github.com/aws-cloudformation/cfn-python-lint ?

As for this plugin it may be possible via https://www.jetbrains.com/help/idea/command-line-code-inspector.html, but I haven't checked it myself.
