### ISSUE TITLE
False positive on error checking

### ISSUE THREAD

**Issue by chadneal** [shalupov/idea-cloudformation#17]
The following is syntax correct but fails within the IDE
![screen shot 2014-03-30 at 2 59 24 pm](https://cloud.githubusercontent.com/assets/2634720/2562498/35bc0f68-b84e-11e3-804b-3eaf5d512c14.png)

        "VPCSGlocal"          : {
            "Type"      : "AWS::EC2::SecurityGroup",
            "Properties": {
                "GroupDescription"   : "Allow local traffic",
                "VpcId"              : {
                    "Ref": "VPC"
                },
                "SecurityGroupEgress": [
                    {
                        "IpProtocol": "udp",
                        "FromPort"  : "53",
                        "ToPort"    : "53",
                        "CidrIp"    : "0.0.0.0/0"
                    }
                ]
            }
        },
        "VPCSGlocalIngressAll": {
            "Type"      : "AWS::EC2::SecurityGroupIngress",
            "Properties": {
                "GroupId"              : {
                    "Ref": "VPCSGlocal"
                },
                "IpProtocol"           : "-1",
                "SourceSecurityGroupId": {
                    "Ref": "VPCSGlocal"
                }
            }
        },
        "VPCSGlocalEgressAll" : {
            "Type"      : "AWS::EC2::SecurityGroupEgress",
            "Properties": {
                "GroupId"              : {
                    "Ref": "VPCSGlocal"
                },
                "IpProtocol"           : "-1",
                "SourceSecurityGroupId": {
                    "Ref": "VPCSGlocal"
                }
            }
        },

**Comment by shalupov** [comment]
Fixed a long time ago
