### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by jdstuart** [shalupov/idea-cloudformation#35]
Can I get some guidance on how to use this plugin? I tried running it on IntelliJ 14.1.3 but couldn't get it to work. I'll be willing to write documentation for it if someone can point me in the right direction.

**Comment by shalupov** [comment]
Thank you, it would be very nice. I'll write here a brief introduction in a couple of days then.

**Comment by krimsonkla** [comment]
I had the same result as @jdstuart. Attempted to use this in IntelliJ and WebStorm. I even attempted from source, not the available plugin. In both cases the plugin shows as enabled however AWS templates are not available as a file type association. Instead .template files are changed from JSON to Text. Not sure if this is a documentation problem (read user error ;) ) or....

IntelliJ Version 14.1.4

**Comment by shalupov** [comment]
@jdstuart @krimsonkla I've fixed file type detection code. it was failing when *.template was already assigned to JSON. Please try new version 0.3.21 (already on plugins site)

**Comment by shalupov** [comment]
Documentation notes:

* Install plugin from File -> Settings -> Plugins -> Browse repositories -> AWS CloudFormation support
* Open any *.template file with CloudFormation JSON inside
* There should be number of features available:
  * Template validation
    * Overall file structure
    * References to resources, conditions, parameters, mappings
    * Resource types and properties
  * File structure (aka Go to member) (Ctrl-F12 on Windows): fast jump to any entity in the file
  * Completion in Ref clause
  * Completion of resources types and properties
  * Live template for Ref clause: type "ref" and press Tab
  * Click on any reference to jump to its definition
  * Format file

**Comment by krimsonkla** [comment]
@shalupov I was going to dig when I had more free time. Your fast! Works perfectly!
