### ISSUE TITLE
How would you feel about adding a template format MetaData Section?

### ISSUE THREAD

**Issue by rackerroush** [shalupov/idea-cloudformation#37]
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/metadata-section-structure.html

I like to add details at the top of the template in the "AWSTemplateFormatVersion" section:

 "Metadata": {
    "Version": "V1.0",
    "LastUpdated": "Jan 1st 2015",
    "UpdatedBy": "First Last",
    "Comments": "Initial Draft"
  },

**Comment by rackerroush** [comment]
Here is maybe a better visual about what I am talking about:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html

**Comment by shalupov** [comment]
Fixed. I've updated plugin on plugins.jetbrains.com too
