### ISSUE TITLE
VpcPeeringConnectionId shown as invalid resource in cloudformation template

### ISSUE THREAD

**Issue by s4mur4i** [shalupov/idea-cloudformation#41]
Hy,

I have an aws cloudformation template. Syntax checker shows an invalid entry which should be valid:

Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-route.html 

Code:
"PeeringRoute": {
"Type": "AWS::EC2::Route",
"Properties": {
"DestinationCidrBlock": "SomeCidr",
"RouteTableId": "Someroutetable",
"VpcPeeringConnectionId": {
"Ref": "VPCPeeringConnection"
}
}
}, 
The VpcPeeringConnectionId is marked invalid. But when uploading the template to aws it is valid and works. According to documentation it is also valid. 

Thanks 
Krisztian

**Comment by laurrentt** [comment]
+1

**Comment by shalupov** [comment]
Fixed, thanks!
