### ISSUE TITLE
Bug in validating "AWS::CloudFormation::Init"

### ISSUE THREAD

**Issue by tianx2** [shalupov/idea-cloudformation#44]
On the latest version of the plugin, it seems like there isn't a validation error on when checking `AWS::CloudFormation::Init`.

Sample Input:
```json
  "LaunchConfig": {
      "Type": "AWS::AutoScaling::LaunchConfiguration",
      "Metadata": {
        "AWS::Cloudformation::Init": {
          "configSets": {
            "install_stuff": [ "download", "install" ]
          },
        }
      },
      "Properties": {}
    }
```

Expected error on `AWS::Cloudformation::Init` should be `AWS::CloudFormation::Init` with capitalized F in CloudFormation. Not sure how possible this is to fix because technically you could put any value in the `Metadata` section for any type of resource.

**Comment by shalupov** [comment]
Well, I don't know how to fix this. That's not really a bug as you said.
