### ISSUE TITLE
Unknown CloudFormation resource type for "AWS::DirectoryService::MicrosoftAD"

### ISSUE THREAD

**Issue by danigui** [shalupov/idea-cloudformation#47]
Sample output,
{
  "Type" : "AWS::DirectoryService::MicrosoftAD",
  "Properties" : {
    "CreateAlias" : Boolean,
    "EnableSso" : Boolean,
    "Name" : String,
    "Password" : String,
    "ShortName" : String,
    "VpcSettings" : VpcSettings
}

**Comment by shalupov** [comment]
fixed in 0.3.47
