### ISSUE TITLE
Unsupported property (NotificationConfiguration)

### ISSUE THREAD

**Issue by Jalober** [shalupov/idea-cloudformation#51]
Property "NotificationConfiguration" in resource type "AWS::AutoScaling::AutoScalingGroup" is not supported by plugin, but it is supported by AWS CloudFormation service. Plugin marks it like error.

**Comment by shalupov** [comment]
It's called "NotificationConfigurations" in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html

but probably CFN supports it anyway

**Comment by shalupov** [comment]
ok, according to http://vstoolkit.amazonwebservices.com/CloudFormationSchema/CloudFormationV1.schema they are both supported
