### ISSUE TITLE
Unknown resource type property: Tags for AWS::CloudFormation::Stack

### ISSUE THREAD

**Issue by darken99** [shalupov/idea-cloudformation#54]
PyCharm:
- 5.0.4, build PC-143.1919, Plugin version 0.3.52
- 5.1, build PC-145.256.43 - no compatible plugin

Error is displayed when trying to use 'Tags' property inside 'AWS::CloudFormation::Stack' resource type

**Comment by shalupov** [comment]
Please update the plugin to 0.4.18, which is now compatible with PyCharm 2016.1
