### ISSUE TITLE
JSON files not recognised

### ISSUE THREAD

**Issue by darrenhaken** [shalupov/idea-cloudformation#58]
Do I need to configure the JSON files in some way for it to detect its a Cloud Formation template?

**Comment by shalupov** [comment]
No, you shouldn't do anything, it's detected automatically by checking first 1K bytes of a template for "AWSCloudFormation" string

Could you attach your file here? Or try to open any examples from Amazon

**Comment by blair-anson** [comment]
Only works for me if the file has a `.template` extension, and the template version is at the top of the file...
```
{
  "AWSTemplateFormatVersion" : "2010-09-09",
....
```

**Comment by shalupov** [comment]
@blair-anson Which extension do you have and where do you store template version?

**Comment by blair-anson** [comment]
@shalupov if I have a file extension other than `.template`  it doesn't work for me. Also the AWSTemplateFormatVersion must be specified in the file...I just put it as the first item at the root of the json structure (as per my previous message).

I'm fine with those constraints, but if anyone else has the same issue I posted this message to help them.

**Comment by shalupov** [comment]
Ok, closing the issue
