### ISSUE TITLE
"AWS::ApiGateway" support is missing

### ISSUE THREAD

**Issue by ayavorsk2000-gmail** [shalupov/idea-cloudformation#65]
Hi,
great plugin, use it daily! Would it be possible to add support for "AWS::ApiGateway::*" elements? They are highlighted as syntax errors at the moment.

Thanks!

Example: 

// type is not understood
 "resourceDrivers": {
      "Type": "AWS::ApiGateway::Resource",
      "Properties": {
        "RestApiId" : {"Ref": "apiEvconcierge"},
        "ParentId": { "Fn::GetAtt": ["apiEvconcierge", "RootResourceId"] },
        "PathPart": "drivers"
      }
    },

// function name attribute is not understood for lambda

 "lambdaEvconcierge": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Handler": "com.fngn.evconcierge.lambda.LambdaHandler::handleRequest",
        "Role": {"Fn::Join": ["", ["arn:aws:iam::", { "Ref" : "AWS::AccountId"}, ":role/", {"Ref": "roleLambdaExecution"}]]},
        "Description": {"Fn::Join": ["", ["Cloud formation lambda generated for ", {"Ref": "projectName"}]]},
        "FunctionName": {"Fn::Join": ["", [{"Ref": "projectName"}, "-lambda"]]},
        "MemorySize": 512,
        "Timeout": 15,
        "Code": {
          "S3Bucket": {"Fn::Join": ["", ["com.fngn.", {"Ref": "accountType"}]]},
          "S3Key": {"Fn::Join": ["", [{"Ref": "projectName"}, "/", {"Ref": "lambdaCode"}]]}
        },
        "Runtime": "java8"
      }
    },

**Comment by shalupov** [comment]
Hi!

Please update your plugin to 0.4.30 and check again

**Comment by ayavorsk2000-gmail** [comment]
Hi!

IntelliJ shows only version 0.3.53 as the latest version. Any idea how to upgrade to 4.30?

GitHub also shows 0.3.53 as the latest release.

Thanks,
Alex

**Comment by shalupov** [comment]
Which IntelliJ version do you have? I think 0.4 branch is available since 2016.1

If you don't have a license for it, it's not a problem, AWS CloudFormation plugin will run on IDEA Community Edition too

**Comment by ayavorsk2000-gmail** [comment]
I use a community edition, version 15.0.6. From the plugins page, it shows 0.3.53 for AWS Cloud Formation plugin as the latest available. I tried re-installing the plugin and it puts that same version back on. 

Is there a different way to install the plugin?

**Comment by shalupov** [comment]
Can you update to IDEA Community 2016.1 or later (current version is 2016.2.1)?
You'll see new plugin version there.

See https://plugins.jetbrains.com/plugin/7371 for plugin versions list

**Comment by ayavorsk2000-gmail** [comment]
Thanks, that worked. For some reason my IntelliJ was not offering an upgrade to 2016.1 automatically, so I had to reinstall it. Thanks for fixing the plugin - very useful.
