### ISSUE TITLE
"RoleName" property for type AWS::IAM::Role

### ISSUE THREAD

**Issue by tianx2** [shalupov/idea-cloudformation#66]
It was recently announced that you can specify custom names for IAM roles in cloudformation - https://aws.amazon.com/about-aws/whats-new/2016/07/aws-cloudformation-adds-support-for-aws-iot-and-additional-updates/

This new property is marked "unknown resource type property" in the latest version of the plugin. I appreciate this great plugin and hope this can get fixed quickly.

Adding documentation also for reference - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html

**Comment by shalupov** [comment]
Which version do you use? Only 0.4.30 should be fresh enough

**Comment by tianx2** [comment]
I'm using version `0.3.53`. I admit I'm not using the latest version of IntelliJ. Does `0.4.30` only for the latest version of IntelliJ? My version of IntelliJ is `14.1.7`.

**Comment by shalupov** [comment]
It works from 2016.1

**Comment by shalupov** [comment]
(and in Community Edition too, so you don't need to buy anything)

**Comment by tianx2** [comment]
Confirmed it works on the latest version of IntelliJ. Thanks so much for the help!
