### ISSUE TITLE
New property "ElasticsearchVersion" for AWS::Elasticsearch::Domain

### ISSUE THREAD

**Issue by AurelienR** [shalupov/idea-cloudformation#72]
Tell me if i am wrong, but "ElasticsearchVersion" has just been added as a AWS::Elasticsearch::Domain property.
See: 
[Cloudformation elasticsearch doc](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-elasticsearchversion)
It would be nice if this property was recognized for the template validation :)

Thanks!

**Comment by digitalsanctum** [comment]
+1
