### ISSUE TITLE
Make use of the AWS CloudFormation Resource Specification

### ISSUE THREAD

**Issue by timmattison** [shalupov/idea-cloudformation#76]
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html

Being able to ingest this content would allow you to automatically support new features as they're added.  Just wanted to make you aware that this is now available.

**Comment by hoegertn** [comment]
see #74

**Comment by timmattison** [comment]
Oops, sorry for the dupe

-- 
Tim Mattison
