### ISSUE TITLE
Yaml !GetAtt not working

### ISSUE THREAD

**Issue by simon-morgan** [shalupov/idea-cloudformation#78]
First, thanks so much for getting Yaml support as per #55 - simply brilliant.

However, writing a template today yielded the following:

![screen shot 2017-03-01 at 4 24 18 pm](https://cloud.githubusercontent.com/assets/2461010/23447032/2378545a-fe9c-11e6-81da-7e51d05cd191.png)

I uploaded the template and it was executed by cfn without issue.

Seems like a small bug.  Let me know if I can help.  Thanks again. Simon

**Comment by shalupov** [comment]
Fixed in 0.5.7

**Comment by simon-morgan** [comment]
@shalupov thanks so much for fixing this.  Just brought up my cfn yaml templates and all the red is gone.  Brilliant. Thanks again.
