### ISSUE TITLE
Yaml - GetAtt - 2 Levels of Attributes (marked like error)

### ISSUE THREAD

**Issue by mhernandez-netquest** [shalupov/idea-cloudformation#79]
Hi!

First, thanks again for you effort.

I attached an Image showing that when we are using 2 levels of Attributes with GetAtt.

This is an usual pattern, at least we think it is :), to retrieve outputs from nested stacks.

Like you can see in the image, after the ",", its not an space, its the only way it works.

Many thanks in advance.

![cloudformation 2017-03-24 17-17-43](https://cloud.githubusercontent.com/assets/22744560/24303377/054a82e2-10b6-11e7-91e3-6eb4cbf301cc.png)

**Comment by shalupov** [comment]
According to fixed issue https://github.com/aws/aws-cli/pull/2332 right way is 
`!GetAtt IAMStack.Outputs.DevelopersIamGroup`

Where have you seen the comma? Any references to examples, documentation or code would be welcome

**Comment by shalupov** [comment]
supported `!GetAtt IAMStack.Outputs.DevelopersIamGroup` in 0.5.7

**Comment by mhernandez-netquest** [comment]
You are right, now it's working perfectly from the CLI using two dots.

I will keep an eye into AWSCLI Repo.

Many thanks.
