### ISSUE TITLE
!Split not recognized 

### ISSUE THREAD

**Issue by mhernandez-netquest** [shalupov/idea-cloudformation#83]
Hi,

Here two examples of !Split:

`SubnetId:           !Select [0, !Split ["," , !ImportValue BiPublicSubnetIDs]]`

This one it's marked with an error because !Select expects an array and !Split is not implemented yet.

And this one it's just because it's not recognized:

`SubnetIds: !Split [',', !ImportValue BiPrivateSubnetIDs]`

Thanks a lot.

**Comment by shalupov** [comment]
Fixed in 0.5.24, thanks for spotting this
