### ISSUE TITLE
AWS::Transform, AWS::Include functions not available.

### ISSUE THREAD

**Issue by sdole** [shalupov/idea-cloudformation#87]
AWS has two newer functions available:
AWS::Serverless Transform
AWS::Include

Can you add these two as well? The main documentation page is: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html

**Comment by shalupov** [comment]
serverless supported in 0.5.39

**Comment by shalupov** [comment]
AWS::Include will be tracked as #93
