### ISSUE TITLE
Plugin Error: Unable to Load in PyCharm [Version Details Inside]

### ISSUE THREAD

**Issue by yks0000** [shalupov/idea-cloudformation#89]
PyCharm Version: 

PyCharm Community Edition 2017.1.1
Build #PC-171.4163.6, built on April 11, 2017
JRE: 1.8.0_112-release-736-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4

Plugin Error
				Problems found loading plugins:
				Plugin "AWS CloudFormation" was not loaded: required plugin "org.jetbrains.plugins.yaml" not installed.
				Disable AWS CloudFormation
				Open plugin manager

**Comment by wisco24** [comment]
This is the same as Issue #82

**Comment by shalupov** [comment]
Yes, duplicates #82
