### ISSUE TITLE
find usages not working 

### ISSUE THREAD

**Issue by sdole** [shalupov/idea-cloudformation#91]
In the latest release of the yaml plugin find usages (Ctrl + Alt + F7) is not working. Does not do anything.

**Comment by shalupov** [comment]
It just not working since corresponding provider is missing for YAML, I'll try to fix it in IDEA 2017.2

**Comment by danieljimenez** [comment]
One of my favorite features, still rockin that JSON until this is implemented :)

**Comment by shalupov** [comment]
fixed in IDEA master, hopefully it'll be backported for 2017.1.1
https://github.com/JetBrains/intellij-community/commit/2f5c8f87fd2a2b312abc0eb5238b9f8e30816c7b

**Comment by danieljimenez** [comment]
This is seriously one of themost useful time saving plugins in the entire IntelliJ community. I work in Java, Python, iOS, several build systems, teamcity and a tiny bit of web sometimes, but this single plugin has saved me more hours than all of those combined. Thank you so much for adding YAML support.

**Comment by danieljimenez** [comment]
Hi, I'm on 2017.2.1 and still seeing this issue :(

```IntelliJ IDEA 2017.2.1
Build #IU-172.3544.35, built on July 31, 2017
Licensed to ForeFlight LLC / Daniel Jimenez
You have a perpetual fallback license for this version
Subscription is active until July 31, 2018
JRE: 1.8.0_152-release-915-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6```

**Comment by shalupov** [comment]
sorry, not there yet, there are some unsolved problems with WordsScanner implementation

**Comment by shalupov** [comment]
Unfortunately it's requires some changes in other IDEA code as well, so it's postponed for 2017.3

**Comment by shalupov** [comment]
It works for me in 2018.1 and 2018.2.
