### ISSUE TITLE
!Sub with 2 arguments inside Fn::Base64: marked as violation "Base64 reference expects 1 argument"

### ISSUE THREAD

**Issue by aindenko** [shalupov/idea-cloudformation#95]
Hello,

Really nice and useful plugin for CloudFormation routine work :) 

So, I've small issue. When I use !Sub with 2 arguments inside Fn::Base64: it is marked as violation.
See screenshot: https://puu.sh/vD15p/aa9b163ead.png
When I use full Sub syntax - works fine

Regards,
Andriy

**Comment by shalupov** [comment]
Fixed in 0.5.30
