### ISSUE TITLE
PlugIn no longer compatible with WebStorm EAP (2017.2)

### ISSUE THREAD

**Issue by jamiepeloquin** [shalupov/idea-cloudformation#97]
Hi - It seems that this plugin is no longer compatible with WebStorm (version info below):
WebStorm 2017.2 EAP
Build #WS-172.2103.10, built on May 10, 2017
WebStorm EAP User
Expiration date: June 9, 2017
JRE: 1.8.0_152-release-845-b3 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by hoegertn** [comment]
same for IDEA 2017.2 EAP

**Comment by shalupov** [comment]
Fixed in 0.5.30
