### ISSUE TITLE
AWS::Function "Lambda" Tags property not recognised

### ISSUE THREAD

**Issue by eduardev** [shalupov/idea-cloudformation#98]
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-tags

**Comment by shalupov** [comment]
fixed by https://github.com/shalupov/idea-cloudformation/commit/e3ee3c937728d250a8498a1b778163923f9769c2

**Comment by shalupov** [comment]
Fixed in 0.5.30
